name: Deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  release-and-publish-package:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ant-design-blazor'

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Publish 🎉
        run: |
          cp -rf .github/gh-pages/* .github/gh-pages/.nojekyll .github/gh-pages/.spa ./src/AntDesign.TabView/wwwroot
          dotnet publish ./src/AntDesign.TabView/AntDesign.TabView.csproj -c Release -o cargo
        env:
          PACKAGE_VERSION: ${{ steps.pack.outputs.package_version }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: cargo/wwwroot
